"use client";

import { ArrowLeft, CarFront, Loader2, Save } from "lucide-react";
import Link from "next/link";
import { useState } from "react";
import { useRouter } from "next/navigation";

type DriverForm = { name: string; email: string; phone: string; password: string; licenseNumber: string; licenseType: string; licenseExpiry: string; experienceYears: string };
const emptyForm: DriverForm = { name: "", email: "", phone: "", password: "", licenseNumber: "", licenseType: "", licenseExpiry: "", experienceYears: "" };

export default function AddDriverPage() {
  const router = useRouter();
  const [form, setForm] = useState(emptyForm);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState("");
  const update = (event: React.ChangeEvent<HTMLInputElement>) => setForm({ ...form, [event.target.name]: event.target.value });
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); setError(""); try { const response = await fetch("/api/chc/drivers", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Unable to add driver"); router.push("/dashboard/chc/drivers"); } catch (err: unknown) { setError(err instanceof Error ? err.message : "Unable to add driver"); setSaving(false); } };
  const inputClass = "mt-2 h-12 w-full rounded-xl border border-slate-200 bg-slate-50 px-4 font-normal outline-none focus:border-emerald-500 focus:bg-white";
  return <div className="mx-auto max-w-3xl px-6 py-10 sm:px-10"><Link href="/dashboard/chc/drivers" className="flex items-center gap-2 text-sm font-semibold text-slate-500 hover:text-emerald-700"><ArrowLeft className="h-4 w-4" /> Back to drivers</Link><div className="mt-10"><div className="flex h-12 w-12 items-center justify-center rounded-xl bg-emerald-100 text-emerald-700"><CarFront className="h-6 w-6" /></div><p className="mt-6 text-sm font-semibold text-emerald-700">Team operations</p><h2 className="mt-2 text-4xl font-black tracking-tight">Add driver</h2><p className="mt-3 text-slate-500">Create a driver account and assign them to your centre.</p></div>{error && <p className="mt-8 rounded-xl bg-rose-50 p-4 text-sm font-medium text-rose-700">{error}</p>}<form onSubmit={submit} className="mt-8 space-y-7 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8"><div><h3 className="text-lg font-bold">Account details</h3><div className="mt-5 grid gap-6 sm:grid-cols-2"><label className="text-sm font-semibold text-slate-700">Full name *<input name="name" required value={form.name} onChange={update} className={inputClass} /></label><label className="text-sm font-semibold text-slate-700">Phone *<input name="phone" required value={form.phone} onChange={update} className={inputClass} /></label><label className="text-sm font-semibold text-slate-700">Email *<input name="email" type="email" required value={form.email} onChange={update} className={inputClass} /></label><label className="text-sm font-semibold text-slate-700">Temporary password *<input name="password" type="password" minLength={6} required value={form.password} onChange={update} className={inputClass} /></label></div></div><div><h3 className="text-lg font-bold">Driver credentials</h3><div className="mt-5 grid gap-6 sm:grid-cols-2"><label className="text-sm font-semibold text-slate-700">License number *<input name="licenseNumber" required value={form.licenseNumber} onChange={update} className={inputClass} /></label><label className="text-sm font-semibold text-slate-700">License type<input name="licenseType" value={form.licenseType} onChange={update} placeholder="e.g. Heavy Motor Vehicle" className={inputClass} /></label><label className="text-sm font-semibold text-slate-700">License expiry<input name="licenseExpiry" type="date" value={form.licenseExpiry} onChange={update} className={inputClass} /></label><label className="text-sm font-semibold text-slate-700">Experience years<input name="experienceYears" type="number" min="0" step="1" value={form.experienceYears} onChange={update} className={inputClass} /></label></div></div><button disabled={saving} className="flex w-full items-center justify-center gap-2 rounded-xl bg-emerald-600 py-3.5 text-sm font-bold text-white transition hover:bg-emerald-700 disabled:opacity-60">{saving ? <Loader2 className="h-5 w-5 animate-spin" /> : <Save className="h-5 w-5" />} {saving ? "Adding driver..." : "Add driver"}</button></form></div>;
}
